require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
    - log/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/bundle/**/*

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/environments/*

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - db/fixtures/**/*
