require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*

inherit_from: .rubocop_todo.yml
