version: '3.3'

services:
  app: &app_base
    build: .
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; ./bin/rails server -b 0.0.0.0" ]
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
      SELENIUM_HOST: chrome
      SELENIUM_POST: 4444
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - chrome
    tty: true
    stdin_open: true

  spring:
    <<: *app_base
    command: [ "bundle", "exec", "spring", "server" ]
    ports: []
    tty: false
    stdin_open: false

  webpacker:
    <<: *app_base
    command: [ "./bin/webpack-dev-server" ]
    ports: []
    tty: false
    stdin_open: false
    depends_on:
      - app

  db:
    image: postgres:11
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd

  chrome:
    image: selenium/standalone-chrome-debug:3.141.59
    volumes:
      - .:/app
      - ./tmp/screenshots:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900

volumes:
  bundle:
  node-modules:
  pg_data:
