version: '3.3'

services:
  app: &rails
    build: .
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; ./bin/rails server -b 0.0.0.0" ]
    environment:
      BUNDLE_PATH: "/bundle"
      POSTGRES_PASSWORD: "passwd"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/bundle
    links:
      - db

  spring:
    <<: *rails
    command:
      ["bin/spring", "start"]

  db:
    image: postgres:11
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "passwd"

volumes:
  bundle:
  pg_data:
