default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: m3_development

test:
  <<: *default
  database: m3_test

production:
  <<: *default
  database: m3_production
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  username: m3
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
