name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3

    - name: Install dependent packages
      run: sudo apt-get install libpq-dev

    - name: Install bundler
      run: gem install bundler

    - name: Build
      run: bundle install --jobs 4 --retry 3

    - name: Lint
      run: bundle exec rubocop

    - name: Spec
      run: bundle exec rspec
