name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: passwd
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3

    - name: Install dependent packages
      run: sudo apt-get install libpq-dev

    - name: Install bundler
      run: gem install bundler

    - name: Build
      run: bundle install --jobs 4 --retry 3 --with test

    - name: Lint
      run: bundle exec rubocop

    - name: Setup Database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load
      env:
        RAILS_ENV: test
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: passwd

    - name: Spec
      run: bundle exec rspec
      env:
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: passwd
