name: CI

on: [push]

jobs:

  prepare:
    runs-on: ubuntu-latest

    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest

    needs: prepare

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: passwd
        ports:
          - 5432:5432
      chrome:
        image: selenium/standalone-chrome:3.141.59
        ports:
          - 4444:4444

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3

    - name: Install dependent packages
      run: sudo apt-get install libpq-dev

    - name: Install bundler
      run: gem install bundler

    - name: Build
      run: |
        bundle install --jobs 4 --retry 3 --with test
        ./bin/yarn
        ./bin/webpack
      env:
        RAILS_ENV: test

    - name: Lint
      run: |
        rubocop
        slim-lint app/views/

    - name: Setup Database
      run: |
        rails db:create
        rails db:schema:load
      env:
        RAILS_ENV: test
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: passwd

    - name: Spec
      run: rspec
      env:
        CI: true
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: passwd
        SELENIUM_HOST: localhost
        SELENIUM_POST: 4444

    - name: Security check
      run: brakeman -4 -A -w 1 -z
